VisualizationADLData/VisualizationADL/Controllers/AlertsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ContosoSite.Models;

namespace ContosoSite.Controllers
{
    public class AlertsController : Controller
    {
        private ContosoUniversityDataEntities db = new ContosoUniversityDataEntities();

        // GET: Alerts
        public ActionResult Index()
        {
            return View(db.Alerts.ToList());
        }

        

        // GET: Alerts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alert alert = db.Alerts.Find(id);
            if (alert == null)
            {
                return HttpNotFound();
            }
            return View(alert);
        }

        // GET: Alerts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Alerts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "AlertId,AlertMessage,CreateDate,ExpirationDate,Accepted,AcceptedDate")] Alert alert)
        {
            if (ModelState.IsValid)
            {
                db.Alerts.Add(alert);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(alert);
        }

        // GET: Alerts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alert alert = db.Alerts.Find(id);
            if (alert == null)
            {
                return HttpNotFound();
            }
            return View(alert);
        }

        // POST: Alerts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "AlertId,AlertMessage,CreateDate,ExpirationDate,Accepted,AcceptedDate")] Alert alert)
        {
            if (ModelState.IsValid)
            {
                db.Entry(alert).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(alert);
        }

        // GET: Alerts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Alert alert = db.Alerts.Find(id);
            if (alert == null)
            {
                return HttpNotFound();
            }
            return View(alert);
        }

        // POST: Alerts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Alert alert = db.Alerts.Find(id);
            db.Alerts.Remove(alert);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

VisualizationADLData/VisualizationADL/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ContosoSite.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

VisualizationADLData/VisualizationADL/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

VisualizationADLData/VisualizationADL/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

VisualizationADLData/VisualizationADL/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<br />
<br />

<div width="100%" height="100%" align="center" valign="center" >

    
   
       

        <img src="@Url.Content("~/Content/Image/ADL.png")" />

        <p><a href="@Url.Action("Index", "Activities")" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>


@*<hr />*@

@*<div>
    @Html.ActionLink("List of students", "Index", "Students")<br />
    @Html.ActionLink("List of enrollments", "Index", "Enrollments")<br />
    @Html.ActionLink("List of alerts", "Index", "Alerts")
</div>*@

@*<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>*@



















<hr/>




<div class="row">
    <div class="col-md-4">
        <a href="@Url.Action("KendoUIGrid", "Activities")">
            <div class="alert alert-danger alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">x</span>
                </button>
                <strong>
                    Hello!
                </strong>
                <span id="span_text">Click here, go to Kendo UI Grid of Activities, you can edit the data, and also export data to Excel</span>
            </div>
        </a>
    </div>
    <div class="col-md-4">
        <a href="@Url.Action("AmPie", "Activities")">
            <div class="alert alert-success alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">x</span>
                </button>
                <strong>
                    Hello!
                </strong>
                <span id="span_text">Click here, go to Pie Chart, you can view summary of activities as Pie Chart, you can also decide which activity not show up</span>
            </div>
        </a>
    </div>
    <div class="col-md-4">

        <a href="@Url.Action("AmBar", "Activities")">
            <div class="alert alert-info alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">x</span>
                </button>
                <strong>
                    Hello!
                </strong>
                <span id="span_text">Click here, go to Bar Chart, you can view summary of activities as Bar Chart, you can also download Bar Chart as image, pdf, etc</span>
            </div>
        </a>
    </div>
</div>






<div class="row">
    <div class="col-md-4">
        <a href="@Url.Action("FilterTable", "Activities")">
            <div class="alert alert-warning alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">x</span>
                </button>
                <strong>
                    Hello!
                </strong>
                <span id="span_text">Click here, go to Filter data and search data</span>
            </div>
        </a>

    </div>
    <div class="col-md-4">
        <a href="@Url.Action("Record1", "Activities")">
            <div class="alert alert-info alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">x</span>
                </button>
                <strong>
                    Hello!
                </strong>
                <span id="span_text">Click here, go to Filter data and search data from 20160803 to 20160822</span>
            </div>
        </a>
    </div>
    <div class="col-md-4">
        <a href="@Url.Action("Index", "Activities")">
            <div class="alert alert-warning alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">x</span>
                </button>
                <strong>
                    Hello!
                </strong>
                <span id="span_text">Click here, go to Index of Activities, which contains multiple functionality</span>
            </div>
        </a>
    </div>
</div>








<div class="row">
    <div class="col-md-4">
        <a href="@Url.Action("Animation", "Activities")">
            <div class="alert alert-success alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">x</span>
                </button>
                <strong>
                    Hello!
                </strong>
                <span id="span_text">Click here, go to Animcation page</span>
            </div>
        </a>

    </div>
    <div class="col-md-4">
        <a href="@Url.Action("AmLine", "Activities")">
            <div class="alert alert-danger alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">x</span>
                </button>
                <strong>
                    Hello!
                </strong>
                <span id="span_text">Click here, go to Line Chart</span>
            </div>
        </a>
    </div>
    <div class="col-md-4">
        <a href="@Url.Action("WorkMap", "Activities")">
            <div class="alert alert-info alert-dismissible fade in" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">x</span>
                </button>
                <strong>
                    Hello!
                </strong>
                <span id="span_text">Click here, go to Google Map</span>
            </div>
        </a>
    </div>
</div>







<style>
  a {
     text-decoration: none ;
  }
a:hover
  {
    color:white;
    text-decoration:none;
    cursor:pointer;
   }
}
</style>